spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=vibe-api
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/vibe}
springdoc.packages-to-scan=com.vibe.interfaces.v1
springdoc.paths-to-match=/api/v1/**
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-exclude=org.springframework.data.mongodb.core.geo